server:
  port: 8080

spring:
  application:
    name: order-api
  kafka:
    bootstrap-servers: kafka1:19092
    consumer:
      group-id: order-api-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.example.dto"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:postgresql://postgres-db1:5432/onlineshop
    username: mara
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

topic:
  name:
    order-created: order_created_topic
    order-updated: order_updated_topic

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.kafka: INFO

